# TP- NumPy - Solution


### Import numpy as np and see the version


In [2]:
import numpy as np

1.21.5


### Create a 1D array (X) of numbers from 0 to 9


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Create a 3×3 numpy array of all True’s

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Extract all odd numbers from array X

array([1, 3, 5, 7, 9])

### Replace all odd numbers in X with -1  without changing X

Modified Array
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array
[0 1 2 3 4 5 6 7 8 9]


### Convert X to a 2D array with 2 rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Generate the following arrays automatically: 
a = array([[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]]
     
b= array[[1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


### Stack arrays a and b vertically

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Stack arrays a and b horizontally

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Get the positions where elements of a and b match

(array([0], dtype=int64), array([1], dtype=int64))

### Get all items between 5 and 10 from array a

array([5, 6, 7, 8, 9])

### Create a 2D array of shape 5x3 to contain random decimal numbers between 1 and 30.

array([[17.73014348, 22.53191098, 19.27533416],
       [17.87342358,  1.59273483,  7.09077075],
       [16.79586147, 23.30433996,  8.27016165],
       [ 9.29097502, 25.71945755, 29.27518831],
       [26.66074551, 11.42572747, 18.36690943]])

### Replace all values greater than 20 to 20 and less than 5 to 5.

array([[10.        , 11.81212934, 10.        ],
       [10.        , 24.07421275, 10.        ],
       [18.36645793, 18.51033163, 10.        ],
       [12.0763599 , 10.        , 26.82193534],
       [29.44670485, 10.        , 26.8258324 ]])

### Read the wind speed column from the "wind_dataset.csv" file as a numpy array


array([13.67, 11.5 , 11.25, ...,  6.  ,  6.25,  2.67])

### Find the mean, median, standard deviation of windspeed

Mean 9.98
Median 10.07
Standard Deviation 4.55


### Create a normalized form of wind's speed whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

array([[ 0.58945293, -0.0744209 ],
       [ 0.4825037 ,  0.16707738],
       [ 0.47018236, -0.06456382],
       ...,
       [ 0.2114342 , -0.08427797],
       [ 0.22375554, -0.08427797],
       [ 0.04731395, -0.08427797]])

### Compute the softmax score of the windspeed
hint:

$softmax (x) =\exp (x)/\sum\exp(x)$

array([1.37050734e-04, 1.56481262e-05, 1.21867729e-05, ...,
       6.39503152e-08, 8.21138302e-08, 2.28898035e-09])

### Verify the sum of the softmax output  (it must sum 1)

0.9999999999999998

### Find the min and max of wind speed

min 1.71


min =  22.0


### Find the most frequent wind speed

10.88

### Sort the windspeed in an descending order and print the largest 10 speeds

array([22.  , 21.17, 20.38, 19.17, 17.83, 17.5 , 17.12, 16.79, 16.62,
       16.5 ])

### Select 4 random windspeed values

### Filter the wind dataset  that has wind speed > 13

### Save the array in a npz file

### Load data from npz file